Repository nadeldrucker/TrafficSwipe, pull requests merged in 2019-12, with the labels that each got.

#35 Gesture characters are working halleluja
  .gitattributes
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/assets/model.tflite
  app/src/main/java/dev/nadeldrucker/trafficswipe/App.java
  app/src/main/java/dev/nadeldrucker/trafficswipe/fragments/StartFragment.java
  app/src/main/java/dev/nadeldrucker/trafficswipe/inference/CharacterRecognizer.java
  app/src/main/java/dev/nadeldrucker/trafficswipe/ui/CharacterDrawView.java
  app/src/main/res/layout/fragment_start.xml
Labels: C: Story

#32 Fixed #28 - view holders not added correctly
  app/src/main/java/dev/nadeldrucker/trafficswipe/ui/RecyclerResultAdapter.java
Labels: C: Bug

#40 Hotfix
  app/src/main/java/dev/nadeldrucker/trafficswipe/dao/transport/model/data/vehicle/Vehicle.java
Labels: P: Critical
